name: hs_legacy
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.7.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - beautifulsoup4=4.12.3
  - brotli-python=1.0.9
  - ca-certificates=2025.8.3
  - catalogue=1.0.0
  - cffi=1.15.1
  - charset-normalizer=3.4.0
  - cymem=2.0.7
  - cython-blis=0.7.6
  - exceptiongroup=1.2.2
  - freetype=2.13.3
  - icu=67.1
  - importlib_metadata=4.11.4
  - importlib_resources=6.0.0
  - ipython=7.15.0
  - ipython_genutils=0.2.0
  - jupyter_server=1.23.4
  - jupyterlab=2.1.5
  - jupyterlab_pygments=0.3.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20250104
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.25
  - libpng=1.6.50
  - libsodium=1.0.18
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libzlib=1.3.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - murmurhash=1.0.9
  - nbclassic=1.1.0
  - nbclient=0.7.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - numpy=1.18.5
  - openssl=3.5.2
  - pandas=1.0.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - plac=0.9.6
  - preshed=3.0.8
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.7.12
  - python-fastjsonschema=2.20.0
  - python_abi=3.7
  - pytz=2024.2
  - readline=8.2
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - setuptools=59.8.0
  - sniffio=1.3.1
  - soupsieve=2.3.2.post1
  - spacy=2.3.5
  - sqlite=3.50.4
  - srsly=1.0.5
  - thinc=7.4.5
  - tinycss2=1.4.0
  - tk=8.6.13
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - wasabi=0.10.1
  - webencodings=0.5.1
  - websocket-client=1.6.1
  - wheel=0.42.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - pip:
      - attrs==19.3.0
      - bleach==3.1.5
      - certifi==2020.6.20
      - chardet==3.0.4
      - colorama==0.4.3
      - cycler==0.10.0
      - decorator==4.4.2
      - defusedxml==0.6.0
      - en-core-web-sm==2.3.1
      - entrypoints==0.3
      - future==0.18.2
      - idna==2.9
      - importlib-metadata==1.6.1
      - ipykernel==5.3.0
      - ipywidgets==7.5.1
      - jedi==0.17.1
      - jinja2==2.11.2
      - joblib==0.15.1
      - json5==0.9.5
      - jsonschema==3.2.0
      - jupyter==1.0.0
      - jupyter-client==6.1.3
      - jupyter-console==6.1.0
      - jupyter-core==4.6.3
      - jupyterlab-server==1.1.5
      - kiwisolver==1.2.0
      - markupsafe==1.1.1
      - mistune==0.8.4
      - nbconvert==5.6.1
      - nbformat==5.0.7
      - notebook==6.0.3
      - packaging==20.4
      - pandocfilters==1.4.2
      - parso==0.7.0
      - pillow==7.1.2
      - prometheus-client==0.8.0
      - prompt-toolkit==3.0.5
      - pygments==2.6.1
      - pyparsing==2.4.7
      - pyrsistent==0.16.0
      - python-dateutil==2.8.1
      - pywinpty==0.5.7
      - pyzmq==19.0.1
      - qtconsole==4.7.5
      - qtpy==1.9.0
      - requests==2.24.0
      - send2trash==1.5.0
      - sentencepiece==0.1.91
      - six==1.15.0
      - terminado==0.8.3
      - testpath==0.4.4
      - threadpoolctl==2.1.0
      - torch==1.5.1
      - torchtext==0.6.0
      - torchvision==0.6.1
      - tornado==6.0.4
      - tqdm==4.46.1
      - traitlets==4.3.3
      - urllib3==1.25.9
      - wcwidth==0.2.5
      - widgetsnbextension==3.5.1
      - zipp==3.1.0
